[llm.sft]
model = "hosted_vllm/AlexCuadron/DSR1-Qwen-14B-8a4e8f3a-checkpoint-64"
temperature = 0.0
api_key = "ddd"
max_input_tokens = 4096
max_output_tokens = 4096
base_url = "http://127.0.0.1:8001/v1/"
custom_llm_provider = "custom_qwen"  # Use our custom provider
timeout = 120  # Increase timeout if needed